module.exports = {
  APL_COMMANDS_TYPE: "Alexa.Presentation.APL.ExecuteCommands",
  APL_DOCUMENT_TYPE: "Alexa.Presentation.APL.RenderDocument",
  APL_DOCUMENT_VERSION: "1.4",
  APL_INTERFACE: "Alexa.Presentation.APL",
  NEXT_QUESTION_AUTO_GENERATED_EVENT: "NextQuestionAutoGeneratedEvent",
  QUESTION_AND_ANSWERS_VIEW_TOKEN: "QuestionAndAnswersViewToken",
  RESULTS_VIEW_TOKEN: "ResultsViewToken",
  USER_INITIATED_CLICK_EVENT: "UserInitiatedClientEvent",
};
